// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnkqEauLHJ_fLVHM7uHGCial4qoZRj8vs',
    appId: '1:105072257978:web:3018efbc507d4ba5b60b83',
    messagingSenderId: '105072257978',
    projectId: 'laza-ecommerce-c820f',
    authDomain: 'laza-ecommerce-c820f.firebaseapp.com',
    storageBucket: 'laza-ecommerce-c820f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2x6Mkdqq63_v-5o82PWAoQMrwtqREIys',
    appId: '1:105072257978:android:4f31297a7aa40f0bb60b83',
    messagingSenderId: '105072257978',
    projectId: 'laza-ecommerce-c820f',
    storageBucket: 'laza-ecommerce-c820f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8MVbxDG7HFiawNSp2IyCB8KPBz_xcO7c',
    appId: '1:105072257978:ios:ff39549711a06bb7b60b83',
    messagingSenderId: '105072257978',
    projectId: 'laza-ecommerce-c820f',
    storageBucket: 'laza-ecommerce-c820f.firebasestorage.app',
    iosBundleId: 'com.example.lazaEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8MVbxDG7HFiawNSp2IyCB8KPBz_xcO7c',
    appId: '1:105072257978:ios:ff39549711a06bb7b60b83',
    messagingSenderId: '105072257978',
    projectId: 'laza-ecommerce-c820f',
    storageBucket: 'laza-ecommerce-c820f.firebasestorage.app',
    iosBundleId: 'com.example.lazaEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnkqEauLHJ_fLVHM7uHGCial4qoZRj8vs',
    appId: '1:105072257978:web:4d2abe07d11e47a7b60b83',
    messagingSenderId: '105072257978',
    projectId: 'laza-ecommerce-c820f',
    authDomain: 'laza-ecommerce-c820f.firebaseapp.com',
    storageBucket: 'laza-ecommerce-c820f.firebasestorage.app',
  );
}
